const levelData = {
	// HIDEOUT
	underBed: {
		type: 'hideout',
		position: [1.9, 0, 1.8],
		scale: [2, 1, 1],
		monsterPosition: [1.5, 0, -0.5],
		monsterInitialPosition: [-0.1, 0, 0.5],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'UnderBed',
		cameraShakingScale: [4, 1, 2.5],
		cameraShakingPosition: [0.5, 0, 0.25],
		headOffset: 1.5,
	},
	underBedsheets: {
		type: 'hideout',
		position: [1.9, 0, 1.8],
		scale: [2, 1, 1],
		monsterPosition: [1.5, 0, -0.5],
		monsterInitialPosition: [-0.1, 0, -0.35],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'UnderBed',
		cameraShakingScale: [4, 1, 2.5],
		cameraShakingPosition: [0.5, 0, 0.25],
		headOffset: 1.5,
	},
	bathroomVent: {
		type: 'hideout',
		position: [2.5, 0, -2.2],
		scale: [2, 1, 2],
		monsterPosition: [2.5, 0, -2.25],
		monsterInitialPosition: [0.8, 0.6, -4.4],
		animation: 'Vent',
	},

	roomVent: {
		type: 'hideout',
		position: [1.5, 0, 4.5],
		scale: [4, 1, 2],
		monsterPosition: [3, 0, 4.6],
		monsterInitialPosition: [3.9, 0.6, 4.85],
		animation: 'Vent',
	},

	bedBasket: {
		type: 'hideout',
		position: [1.9, 0, 1.15],
		scale: [2, 1, 1],
		monsterPosition: [-0.15, 0, 1.25],
		monsterInitialPosition: [-1.33, -0.56, 1.31],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		instantTriggerPosition: [-1.5, -0.93, 1.45],
		instantTriggerScale: [1, 1, 1],
		cameraShakingPosition: [-0.75, 0, 0.75],
		cameraShakingScale: [2.35, 1, 2],
		animation: 'Basket',
		headOffset: Math.PI / 2,
	},

	windowBasket: {
		type: 'hideout',
		position: [0, 0, 2.2],
		scale: [6, 1, 2],
		monsterPosition: [-0.6, 0, 2.4],
		monsterInitialPosition: [-1.39, -0.48, 2.2],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		instantTriggerPosition: [-1.5, 0.5, 2.2],
		instantTriggerScale: [1, 1, 1],
		cameraShakingPosition: [-0.75, 0, 2.56],
		cameraShakingScale: [1.94, 1, 1.6],
		animation: 'Basket',
		headOffset: Math.PI / 2,
	},

	hideoutMirror: {
		type: 'hideout',
		position: [2.5, 0, -2.2],
		scale: [2, 1, 2],
		monsterPosition: [2.5, 0, -2.25],
		monsterInitialPosition: [-5.2, 0, -2.5],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'Idle',
		headOffset: Math.PI / 2,
	},

	behindDoor: {
		type: 'hideout',
		position: [2.5, 0, -1],
		scale: [3, 1, 1],
		monsterPosition: [4.81, 0, -2.4],
		monsterInitialPosition: [3.9, 0, -4.1],
		instantTriggerPosition: [4.1, 0.5, -4.15],
		instantTriggerScale: [1, 1, 1],
		cameraShakingPosition: [3, 0, -1.6],
		cameraShakingScale: [2, 1, 2.5],
		animation: 'BehindDoor',
	},

	footWindow: {
		type: 'hideout',
		monsterPosition: [1.35, 0, 4.85],
		monsterInitialPosition: [1.45, 0, 5.5],
		monsterInitialRotation: [0, Math.PI, 0],
		animation: 'BehindWindow',
		headOffset: Math.PI,
	},

	bathCeiling: {
		type: 'hideout',
		monsterPosition: [-0.59, 4, -4.18],
		monsterInitialPosition: [-0.59, 0, -4.18],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'Bath',
		instantTriggerPosition: [-0.62, 0, -4.4],
		instantTriggerScale: [1.66, 1, 1],
		cameraShakingPosition: [-0.09, 0, -2.88],
		cameraShakingScale: [3, 1, 2.2],
		lookAtPoint: [-0.59, 2, -4.18],
	},

	servingCart: {
		type: 'hideout',
		monsterPosition: [2.24, 0, 3.1],
		monsterInitialPosition: [2.24, 0, 3.1],
		monsterInitialRotation: [0, Math.PI, 0],
		animation: 'Cart',
		instantTriggerPosition: [2, 0, 3],
		position: [1.9, 0, 1.8],
		scale: [2, 1, 1],
		monsterPosition: [1.5, 0, 1],
		cameraShakingScale: [2, 1, 3.4],
		cameraShakingPosition: [3.6, 0, 3.5],
	},

	belowTV: {
		type: 'hideout',
		position: [-1.19, 0, 3.85],
		scale: [1, 1, 1],
		monsterPosition: [-1.19, 0, 3.85],
		instantTriggerPosition: [-1.19, 0, 3.85],
		monsterInitialPosition: [-1.19, 0, 3.24],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'Tv',
		cameraShakingPosition: [-0.62, 0, 4.1],
		cameraShakingScale: [1.1, 1, 0.75],
	},

	// LANDMINE

	landmineMirror: {
		type: 'landmine',
		position: [0.5, 0, -2.8],
		scale: [2, 1, 1],
		monsterPosition: [-3, -0.3, -3.3],
		monsterInitialPosition: [-3, -0.3, -3.3],
		animation: 'Idle',
		instantTriggerPosition: [0.5, 0, -2.3],
		instantTriggerScale: [2, 2, 1],
		lookAtPoint: [-3, 0.7, -3.3],
	},

	nearWindow: {
		type: 'landmine',
		monsterPosition: [3.2, 0, 2],
		monsterInitialPosition: [3.2, 0, 2],
		animation: 'BehindDoor',
		instantTriggerPosition: [2.5, 0, -1],
		instantTriggerScale: [2, 2, 1],
		cameraShakingPosition: [2.8, 0, -2.7],
		cameraShakingScale: [2.4, 1, 2.5],
		lookAtPoint: [3.2, 0.8, 2],
	},

	ceilingCornerCouch: {
		type: 'landmine',
		monsterPosition: [4.35, -0.25, 2.8],
		monsterInitialPosition: [4.25, -0.3, 1.9],
		monsterInitialRotation: [0, 0, 0],
		animation: 'CeilingCornerReverse',
		instantTriggerPosition: [1.5, 0, 2],
		instantTriggerScale: [5, 2, 1],
		cameraShakingPosition: [0.85, 0, 1.15],
		cameraShakingScale: [4.5, 1, 2],
		headOffset: -1.1,
		lookAtPoint: [4.25, 2, 1.9],
	},

	behindCouch: {
		type: 'landmine',
		position: [0, 0, 0],
		scale: [2, 1, 1],
		monsterPosition: [4.3, -0.2, 2.7],
		monsterInitialPosition: [4.03, -1.06, 2.71],
		monsterInitialRotation: [0.43, -2.28, 0.44],
		instantTriggerPosition: [1.9, 0, 2.2],
		instantTriggerScale: [4, 1, 0.8],
		cameraShakingPosition: [0.8, 0, 2.06],
		cameraShakingScale: [4.5, 1, 2],
		animation: 'Vent',
		headOffset: -2.3,
		lookAtPoint: [4.3, -0.2, 2.7],
	},

	behindDesk: {
		type: 'landmine',
		position: [1.9, 0, 0],
		scale: [2, 1, 4],
		monsterPosition: [3, 0, 1],
		monsterInitialPosition: [4.2, -0.1, 1.08],
		monsterInitialRotation: [0, -Math.PI / 2, 0],
		instantTriggerPosition: [1.9, 0, 2.2],
		instantTriggerScale: [4, 1, 0.8],
		cameraShakingPosition: [1, 0, 0.5],
		cameraShakingScale: [5, 1, 3],
		animation: 'Stand',
		headOffset: -Math.PI / 2,
		lookAtPoint: [4.2, -0.1, 1.08],
	},

	insideDesk: {
		type: 'landmine',
		position: [1.9, 0, 0],
		scale: [2, 1, 4],
		monsterPosition: [4, 0, 0.2],
		monsterInitialPosition: [4.2, -0.1, -0.6],
		monsterInitialRotation: [0, -Math.PI / 2, 0],
		instantTriggerPosition: [1.9, 0, 2.2],
		instantTriggerScale: [4, 1, 0.8],
		cameraShakingPosition: [2, 0, 0],
		cameraShakingScale: [3, 1, 6],
		animation: 'Stand',
		headOffset: -Math.PI / 2,
		lookAtPoint: [4.2, -0.1, -0.6],
	},

	ceilingCenter: {
		type: 'landmine',
		instantTriggerPosition: [2.9, 0, -1.5],
		instantTriggerScale: [3.3, 1, 1],
		monsterInitialPosition: [3.01, 2.02, -1.21],
		monsterInitialRotation: [0, 1.61, 0],
		animation: 'Ceiling',
		lookAtPoint: [3.8, 4.02, -1.21],
	},
	// openedDesk: {
	// 	type: 'landmine',
	// 	position: [2.9, 0, -2.69],
	// 	scale: [3, 1, 4],
	// 	monsterPosition: [0, 0, 10],
	// 	monsterInitialPosition: [4.11, 0, 0.382],
	// 	monsterInitialRotation: [0, -Math.PI / 2, 0],
	// 	instantTriggerPosition: [1.9, 0, -1.28],
	// 	instantTriggerScale: [4, 1, 0.8],
	// 	cameraShakingPosition: [1.62, 0, -3.57],
	// 	cameraShakingScale: [2.5, 1, 2.5],
	// 	cameraShakingRotation: [0, -0.93, 0],
	// 	animation: 'Stand',
	// 	lookAtPoint: [4.2, -0.1, 0.24],
	// },

	behindServingCart: {
		type: 'landmine',
		monsterPosition: [3, 0, 4],
		monsterInitialPosition: [2.3, -0.2, 4.08],
		monsterInitialRotation: [0, -Math.PI / 2, 0],
		instantTriggerPosition: [1.9, 0, 2.2],
		instantTriggerScale: [4, 1, 0.8],
		cameraShakingPosition: [1.9, 0, 3],
		cameraShakingScale: [2, 1, 4],
		animation: 'Stand',
		headOffset: -Math.PI / 2,
		lookAtPoint: [2.2, 0.5, 4.08],
	},

	bathroomCorner: {
		type: 'landmine',
		position: [1.9, 0, 0],
		scale: [2, 1, 4],
		monsterPosition: [1.14, 10, -3.7],
		instantTriggerPosition: [1, 0, -3],
		instantTriggerScale: [1, 1, 1.8],
		monsterInitialPosition: [1.14, 0, -3.7],
		monsterInitialRotation: [0, 0, 0],
		animation: 'Stand',
		lookAtPoint: [1.14, 0, -3.7],
	},

	// bedCorner: {
	// 	type: 'landmine',
	// 	deathReason: 'If you see the client, run away',
	// 	position: [1, 0, -1],
	// 	scale: [1, 1, 1.2],
	// 	monsterPosition: [0.25, 0, -0.66],
	// 	monsterInitialPosition: [-0.07, 1.17, -1.5],
	// 	monsterInitialRotation: [0, -1.64, Math.PI],
	// 	animation: 'Ceiling',
	// 	instantTriggerPosition: [1.5, 0, -0.53],
	// 	instantTriggerScale: [5, 2, 1],
	// 	cameraShakingPosition: [2.61, 0, -1],
	// 	cameraShakingScale: [4, 1, 2],
	// },

	// SONAR

	sonarBathroom: {
		type: 'sonar',
		monsterPosition: [0, 0, 10],
		monsterInitialPosition: [0.3, 0, -2.6],
		animation: 'Crouch',
		sound: true,
		lookAtPoint: [0.3, 0, -2.6],
	},

	// sonarWindow: {
	// 	type: 'sonar',
	// 	deathReason: 'If you hear the client, run away',
	// 	monsterPosition: [1.35, 0, 8],
	// 	monsterInitialPosition: [1.52, 0, 6.3],
	// 	monsterInitialRotation: [0, Math.PI, 0],
	// 	animation: 'Crouch',
	// 	sound: true,
	// 	headOffset: Math.PI,
	// },

	// sonarBath: {
	// 	type: 'sonar',
	// 	deathReason: 'If you hear the client, run away',
	// 	monsterPosition: [1.35, 0, 8],
	// 	monsterInitialPosition: [-1, 0, -4.46],
	// 	monsterInitialRotation: [0, Math.PI / 7, 0],
	// 	animation: 'Crouch',
	// 	sound: true,
	// 	headOffset: Math.PI / 7 + 0.05,
	// },

	// sonarDesk: {
	// 	type: 'sonar',
	// 	deathReason: 'If you hear the client, run away',
	// 	monsterPosition: [1.35, 0, 8],
	// 	monsterInitialPosition: [4.06, 0, 0.368],
	// 	monsterInitialRotation: [0, -Math.PI / 2, 0],
	// 	animation: 'Stand',
	// 	sound: true,
	// 	headOffset: -Math.PI / 2,
	// },

	// sonarNightstand: {
	// 	type: 'sonar',
	// 	deathReason: 'If you hear the client, run away',
	// 	monsterPosition: [1.35, 0, 8],
	// 	monsterInitialPosition: [-1.45, 0, -1.28],
	// 	monsterInitialRotation: [0, Math.PI / 2, 0],
	// 	animation: 'Stand',
	// 	sound: true,
	// 	headOffset: Math.PI / 2,
	// },

	// CLAYMORE
	claymoreBath: {
		type: 'claymore',
		monsterPosition: [0, 0, 10],
		monsterInitialPosition: [-0.8, 0, -4.45],
		animation: 'Crouch',
		lookAtPoint: [-0.8, 0, -4.45],
	},

	claymoreDesk: {
		type: 'claymore',
		position: [1.9, 0, 0.43],
		scale: [2.2, 1, 2.5],
		monsterPosition: [0, 0, 10],
		monsterInitialPosition: [4.06, 0, 0.382],
		monsterInitialRotation: [0, -Math.PI / 2, 0],
		animation: 'Stand',
		headOffset: -Math.PI / 2,
		lookAtPoint: [4.06, 0, 0.368],
	},

	claymoreNightstand: {
		type: 'claymore',
		position: [1.9, 0, 0.43],
		scale: [2.2, 1, 2.5],
		monsterPosition: [0, 0, 10],
		monsterInitialPosition: [-1.45, 0, -1.28],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'Stand',
		headOffset: Math.PI / 2,
		lookAtPoint: [-1.45, 0, -1.28],
	},

	claymoreWindow: {
		type: 'claymore',
		monsterPosition: [0, 0, 10],
		monsterInitialPosition: [1.52, 0, 6.3],
		monsterInitialRotation: [0, 0, 0],
		animation: 'Crouch',
		lookAtPoint: [1.52, 0, 6.3],
	},

	// claymoreBathroom: {
	// 	type: 'claymore',
	// 	deathReason: 'Close the door quickly before it attacks you',
	// 	monsterPosition: [0, 0, 10],
	// 	monsterInitialPosition: [0.3, 0, -2.6],
	// 	monsterInitialRotation: [0, 0, 0],
	// 	animation: 'Crouch',
	// 	lookAtPoint: [0.3, 0, -2.6],
	// },

	// claymoreMainDoor: {
	// 	type: 'claymore',
	// 	deathReason: 'Close the door quickly before it attacks you',
	// 	monsterPosition: [0, 0, 10],
	// 	monsterInitialPosition: [0.3, 0, -2.6],
	// 	monsterInitialRotation: [0, 0, 0],
	// 	animation: 'Crouch',
	// 	lookAtPoint: [0.3, 0, -2.6],
	// },

	// claymoreBathroomDoor: {
	// 	type: 'claymore',
	// 	deathReason: 'Close the door quickly before it attacks you',
	// 	monsterPosition: [0, 0, 10],
	// 	monsterInitialPosition: [0.3, 0, -2.6],
	// 	monsterInitialRotation: [0, 0, 0],
	// 	animation: 'Crouch',
	// 	lookAtPoint: [0.3, 0, -2.6],
	// },

	// HUNTER
	hunterLivingRoom: {
		type: 'hunter',
		position: [2.2, 0, 3],
		scale: [2.5, 0.5, 2],
		monsterPosition: [1.5, 0, 4],
		monsterInitialPosition: [-0.5, 0, 1.91],
		monsterInitialRotation: [0, 0, 0],
		animation: 'Wall',
	},

	hunterCeilingLivingRoom: {
		type: 'hunter',
		position: [2.2, 0, 2.7],
		scale: [2.5, 0.5, 2],
		monsterPosition: [1.5, 0, 4],
		monsterInitialPosition: [-1.4, 1.68, 2.08],
		// monsterInitialPosition: [-1.4, 0, 2.08],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'CeilingCrawlIdle',
		ceiling: true,
		headOffset: Math.PI / 1.5,
		// forcedGridX: 265,
		// forcedGridZ: 233,
	},

	hunterNightstand: {
		type: 'hunter',
		position: [2.5, 0, -0.6],
		scale: [2.5, 0.5, 2],
		monsterPosition: [-1.4, 0, -1.2],
		monsterInitialPosition: [-1.45, 0, -1.28],
		monsterInitialRotation: [0, Math.PI / 2, 0],
		animation: 'Stand',
		headOffset: Math.PI / 2,
	},

	hunterWindow: {
		type: 'hunter',
		position: [2.5, 0, -0.6],
		scale: [2.5, 0.5, 2],
		monsterPosition: [1.5, 0, 6],
		monsterInitialPosition: [1.52, 0, 5.85],
		monsterInitialRotation: [0, Math.PI, 0],
		animation: 'BehindWindow',
	},

	firstHunter: {
		type: 'hunter',
		position: [2.85, 0, -1.08],
		scale: [3, 1, 4],
		monsterPosition: [1.5, 0, 4],
		monsterInitialPosition: [-0.75, 0, 4],
		monsterInitialRotation: [0, Math.PI, 0],
		animation: 'Wall',
	},

	// servingCartHunter: {
	// 	type: 'hunter',
	// 	deathReason: 'If you see it, run away and close the door behind you',
	// 	position: [2.85, 0, -1.08],
	// 	scale: [3, 1, 4],
	// 	monsterPosition: [2.24, 0, 3.1],
	// 	monsterInitialPosition: [2.24, 0, 3.1],
	// 	monsterInitialRotation: [0, Math.PI, 0],
	// 	animation: 'Cart',
	// },

	// RAID
	// raidWindow: {
	// 	type: 'raid',
	// 	deathReason: 'If you hear knocking, hide',
	// 	hideObjective: 'window',
	// 	hideSpot: 'window',
	// 	lookAtPoint: [0, 0, 0],
	// },

	// raidBedsheets: {
	// 	type: 'raid',
	// 	deathReason: 'If you hear knocking, hide',
	// 	hideObjective: 'bedsheets',
	// 	hideSpot: 'bedsheets',
	// 	lookAtPoint: [0, 0, 0],
	// },

	raidBottles: {
		type: 'raid',
		hideObjective: 'bottles',
		hideSpot: 'bottles',
		lookAtPoint: [0, 0, 0],
	},

	raidTV: {
		type: 'raid',
		signal: 'tv',
		position: [2, 0, 4],
		scale: [7, 0.5, 2.4],
		lookAtPoint: [2, 0, 1.5],
	},

	raidRadio: {
		type: 'raid',
		signal: 'radio',
		position: [2.5, 0, -0.6],
		scale: [2.5, 0.5, 2],
		lookAtPoint: [2.5, 0, -0.6],
	},

	raidInscriptions: {
		type: 'raid',
		signal: 'inscriptions',
		position: [2, 0, 1.5],
		scale: [2.5, 0.5, 2],
		lookAtPoint: [2, 0, 1.5],
	},

	raidFood: {
		type: 'raid',
		hideObjective: 'food',
		lookAtPoint: [0, 0, 0],
	},

	// raidMirror: {
	// 	type: 'raid',
	// 	deathRson: 'If you see blood inscriptions on the mirror, hide',
	// 	hideObjective: 'mirror',
	// 	hideSpot: 'mirror',
	// },
};

export default levelData;
